"""Stub file for custom_components/reflex_react_joyride/joyride.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
import re
from collections.abc import Callable, Mapping, Sequence
from typing import Any

import reflex as rx
from reflex.components.component import NoSSRComponent
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex_components_core.core.breakpoints import Breakpoints

from .events import JoyrideEvent
from .props import FloatingOptions, Locale, Step, TourOptions, TourStyles

_JSX_ASSET = rx.asset("joyride_tour.jsx", shared=True)
_NODE_KEYS = ("content", "title")
_SNAKE_PART = re.compile("_+([a-zA-Z0-9])")

class Joyride(NoSSRComponent):
    @classmethod
    def create(
        cls,
        *children,
        tour_id: Var[str] | str | None = None,
        steps: Var[list[dict[str, Any]]] | list[dict[str, Any]] | None = None,
        run: Var[bool] | bool | None = None,
        continuous: Var[bool] | bool | None = None,
        initial_step_index: Var[int] | int | None = None,
        step_index: Var[int] | int | None = None,
        scroll_to_first_step: Var[bool] | bool | None = None,
        debug: Var[bool] | bool | None = None,
        options: Var[dict[str, Any]] | dict[str, Any] | None = None,
        locale: Var[dict[str, Any]] | dict[str, Any] | None = None,
        styles: Var[dict[str, Any]] | dict[str, Any] | None = None,
        floating_options: Var[dict[str, Any]] | dict[str, Any] | None = None,
        portal_element: Var[str] | str | None = None,
        nonce: Var[str] | str | None = None,
        tooltip: Callable | Var[Callable] | None = None,
        beacon: Callable | Var[Callable] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_beacon: EventType[()] | EventType[JoyrideEvent] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_error: EventType[()] | EventType[JoyrideEvent] | None = None,
        on_event: EventType[()] | EventType[JoyrideEvent] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | EventType[JoyrideEvent] | None = None,
        on_scroll_start: EventType[()] | EventType[JoyrideEvent] | None = None,
        on_status_change: EventType[()] | EventType[JoyrideEvent] | None = None,
        on_step_after: EventType[()] | EventType[JoyrideEvent] | None = None,
        on_step_before: EventType[()] | EventType[JoyrideEvent] | None = None,
        on_target_not_found: EventType[()] | EventType[JoyrideEvent] | None = None,
        on_tooltip: EventType[()] | EventType[JoyrideEvent] | None = None,
        on_tour_end: EventType[()] | EventType[JoyrideEvent] | None = None,
        on_tour_start: EventType[()] | EventType[JoyrideEvent] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> Joyride:
        """Create a Joyride tour.

        Args:
            *children: Optionally, the steps of the tour, passed positionally.
            tour_id: ------------------------------------------------------------------ content An id for this tour. Required to drive it from Python with the helpers in ``reflex_react_joyride.actions`` (start, next_step, go_to, ...).
            steps: The steps of the tour: Step objects, plain dicts, or a State var holding a list of dicts. ``snake_case`` keys are converted for you.
            run: ----------------------------------------------------------------- playback Run (or stop) the tour. Default: False.
            continuous: Play the steps sequentially with a Next button instead of showing a beacon between them. Default: False.
            initial_step_index: The step to start an uncontrolled tour at. Ignored in controlled mode.
            step_index: Setting this puts the tour in *controlled* mode: react-joyride stops advancing on its own and shows exactly this step, so you keep the index in your State and update it from the events.
            scroll_to_first_step: Also scroll the page for the first step. Default: False.
            debug: Log react-joyride's internal actions to the browser console. Default: False.
            options: ------------------------------------------------------------- presentation Behaviour and theming shared by every step (a TourOptions or a dict).
            locale: The strings used in the tooltip (a Locale or a dict).
            styles: CSS overrides for every element react-joyride renders (a TourStyles or a dict).
            floating_options: Positioning options forwarded to floating-ui (a FloatingOptions or a dict).
            portal_element: Render the tour inside this element instead of the document body.
            nonce: A nonce for the inline styles, for pages with a strict CSP.
            tooltip: ------------------------------------------------------------- render props ``lambda props: rx.card(...)`` replacing the built-in tooltip. ``props`` exposes content, title, index, size, current, total, progress, is_last_step, step_id and step_data.
            beacon: ``lambda props: rx.box(...)`` replacing the built-in beacon.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when the page finished scrolling to a target.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_event: ------------------------------------------------------------------- events Fired for every react-joyride event. The payload is a JoyrideEvent dict.
            on_tour_start: Fired once when the tour starts.
            on_tour_end: Fired when the tour finishes or is skipped. Check ``event["status"]``.
            on_status_change: Fired whenever the tour's status changes (running, paused, finished, ...).
            on_step_before: Fired before a step is shown. In controlled mode this is usually where the index moves forward.
            on_step_after: Fired after a step is closed, with the action that closed it.
            on_beacon: Fired when a step's beacon is rendered.
            on_tooltip: Fired when a step's tooltip is rendered.
            on_scroll_start: Fired when the page starts scrolling to a target.
            on_target_not_found: Fired when a step's target never appeared (see ``target_wait_timeout``).
            on_error: Fired when a step fails, e.g. a ``before`` hook rejected. Read ``event["error"]``.
            **props: Component props.

        Returns:
            The component.

        Raises:
            TypeError: If a render prop is neither a callable nor a Var."""
        ...

joyride = Joyride.create
__all__ = ["FloatingOptions", "Joyride", "Locale", "Step", "TourOptions", "TourStyles", "joyride"]
